// The Stack: generate the PULSE and VALUATION card pages (PBIR) and hide the old versions. Re-runnable.
const fs = require("fs");
const path = require("path");
const R = require("./report_lib");
const A = require("./stack_measures_a");
const B = require("./stack_measures_b");

const DEF = path.resolve(__dirname, "../../DEERE_CYCLEBOOK.Report/definition");
const PAGES = path.join(DEF, "pages");
const OLD = { pulse: "85e801881afa98c3cc2d", valuation: "a24fb8747b56660faf1b" };
const KEEP = { financials: "a656be65e12870af248f", segments: "2f2c922a6f3436a46dd5", cycle: "d91eaac0343ef21a4cd9", modelLab: "65721da987f3a5fa0c79", provenance: "aa26ab00db387bbd7409" };
const NEW = { pulse: "stack_pulse", valuation: "stack_valuation" };
const log = [];

const INDEX = [
  ["PULSE", NEW.pulse], ["FINANCIALS", KEEP.financials], ["SEGMENTS", KEEP.segments], ["THE CYCLE", KEEP.cycle],
  ["MODEL LAB", KEEP.modelLab], ["VALUATION", NEW.valuation], ["SOURCES", KEEP.provenance],
];
const stackIndex = (current) => INDEX.map(([label, target], i) =>
  R.button({ x: 28, y: 84 + i * 133, w: 160, h: 107, z: 400 + i }, label, { page: target }, target === current ? "currentIndex" : "index"));

const desk = () => R.image({ x: 0, y: 0, w: 1920, h: 1080, z: 0 }, "SVG Stack Desk", "Dithered desk with the CYCLEBOOK card stack");
const header = (m, title) => R.image({ x: 256, y: 64, w: 1420, h: 96, z: 100 }, m, `${title} card header with latest close and reporting period`);

const pulse = [
  desk(),
  header("SVG Header PULSE", "PULSE"),
  R.image({ x: 256, y: 172, w: 1420, h: 84, z: 110 }, "SVG Pulse Finding", "Finding: large ag shrinking again while small ag and construction still grow"),
  R.image({ x: 256, y: 264, w: 960, h: 620, z: 120 }, "SVG Pulse Divergence", "Segment net sales growth versus the same quarter a year earlier, last seven fiscal quarters"),
  R.image({ x: 1236, y: 264, w: 440, h: A.pulseLedgerHeight, z: 130 }, "SVG Pulse Ledger", "Latest-quarter actuals, fiscal 2026 guidance and share price"),
  ...R.paintedButton({ x: 836, y: 912, w: 220, h: 56, z: 300 }, "The segments", { page: KEEP.segments }),
  ...R.paintedButton({ x: 1076, y: 912, w: 220, h: 56, z: 302 }, "The cycle", { page: KEEP.cycle }),
  ...R.paintedButton({ x: 1316, y: 912, w: 360, h: 56, z: 304 }, "What the price assumes", { page: NEW.valuation }, "go"),
  R.textbox({ x: 256, y: 926, w: 560, h: 24, z: 140 }, [{ text: "Sources: Deere Q3 FY2026 news release (20 Aug 2026); Nasdaq daily close.", size: 12 }], "Sources"),
  ...stackIndex(NEW.pulse),
];

const valuation = [
  desk(),
  header("SVG Header VALUATION", "VALUATION"),
  R.image({ x: 256, y: 172, w: 1420, h: 84, z: 110 }, "SVG Valuation Finding", "Finding: EPS today's price requires at the selected multiple, against the record"),
  R.image({ x: 256, y: 264, w: 1000, h: 540, z: 120 }, "SVG Valuation Ladder", "EPS the latest close requires at each P/E multiple, against the FY2023 record, management guidance and CYCLEBOOK scenarios"),
  R.image({ x: 1276, y: 264, w: 400, h: B.valuationLedgerHeight, z: 130 }, "SVG Valuation Ledger", "Share price, market cap, trailing P/E and scenario outputs"),
  R.textbox({ x: 256, y: 818, w: 200, h: 26, z: 140 }, [{ text: "Scenario", size: 13, bold: true }]),
  R.image({ x: 256, y: 844, w: 372, h: 64, z: 145 }, "SVG Scenario Keys", "Scenario keys: Bear, Base, Bull"),
  R.buttonSlicer({ x: 256, y: 844, w: 372, h: 64, z: 310 }, "Scenario", "Scenario", 3, "overlay"),
  R.textbox({ x: 640, y: 818, w: 300, h: 26, z: 141 }, [{ text: "P/E multiple", size: 13, bold: true }]),
  R.image({ x: 640, y: 848, w: 1036, h: 80, z: 150 }, "SVG PE Strip", "Implied value per share at each P/E multiple for the selected scenario"),
  R.buttonSlicer({ x: 640, y: 848, w: 1036, h: 80, z: 320 }, "PE Multiple", "P/E Multiple", 11, "overlay"),
  ...R.paintedButton({ x: 1076, y: 946, w: 220, h: 56, z: 330 }, "Back to PULSE", { page: NEW.pulse }),
  ...R.paintedButton({ x: 1316, y: 946, w: 360, h: 56, z: 332 }, "Change the assumptions", { page: KEEP.modelLab }, "go"),
  R.textbox({ x: 256, y: 968, w: 780, h: 44, z: 142 }, [{ text: "Sources: Deere Q3 FY2026 release (20 Aug 2026); Nasdaq daily close. Green = guidance. Stipple = model.", size: 12 }], "Sources and legend"),
  ...stackIndex(NEW.valuation),
];

function writePage(id, displayName, visuals) {
  const dir = path.join(PAGES, id);
  if (fs.existsSync(dir)) fs.rmSync(dir, { recursive: true }); // generated by this script only
  fs.mkdirSync(path.join(dir, "visuals"), { recursive: true });
  fs.writeFileSync(path.join(dir, "page.json"), JSON.stringify(R.page(id, displayName), null, 2), "utf8");
  for (const v of visuals) {
    // Stable names (page + z-order + type) keep git diffs readable across rebuilds.
    v.name = require("crypto").createHash("sha1").update(`${id}:${v.position.z}:${v.visual.visualType}`).digest("hex").slice(0, 20);
    fs.mkdirSync(path.join(dir, "visuals", v.name));
    fs.writeFileSync(path.join(dir, "visuals", v.name, "visual.json"), JSON.stringify(v, null, 2), "utf8");
  }
  log.push(`page ${id} (${displayName}): ${visuals.length} visuals`);
}
writePage(NEW.pulse, "PULSE", pulse);
writePage(NEW.valuation, "VALUATION", valuation);

// Hide the old pages rather than delete them.
for (const id of Object.values(OLD)) {
  const f = path.join(PAGES, id, "page.json");
  const p = JSON.parse(fs.readFileSync(f, "utf8"));
  if (p.visibility !== "HiddenInViewMode") {
    p.visibility = "HiddenInViewMode";
    p.displayName = `${p.displayName} (v1)`;
    fs.writeFileSync(f, JSON.stringify(p, null, 2), "utf8");
    log.push(`hidden old page ${id}`);
  }
}

// Hide the Filters pane for readers: every control lives on the cards.
const reportFile = path.join(DEF, "report.json");
const reportJson = JSON.parse(fs.readFileSync(reportFile, "utf8"));
reportJson.objects = reportJson.objects || {};
reportJson.objects.outspacePane = [{ properties: { expanded: { expr: { Literal: { Value: "false" } } }, visible: { expr: { Literal: { Value: "false" } } } } }];
fs.writeFileSync(reportFile, JSON.stringify(reportJson, null, 2), "utf8");
log.push("report.json: Filters pane hidden");

const pagesFile = path.join(PAGES, "pages.json");
const meta = JSON.parse(fs.readFileSync(pagesFile, "utf8"));
meta.pageOrder = [NEW.pulse, KEEP.financials, KEEP.segments, KEEP.cycle, KEEP.modelLab, NEW.valuation, KEEP.provenance, OLD.pulse, OLD.valuation];
meta.activePageName = NEW.pulse;
fs.writeFileSync(pagesFile, JSON.stringify(meta, null, 2), "utf8");
log.push("pages.json updated");
console.log(log.join("\n"));
